### ISSUE TITLE
Block Submission* never triggers

### ISSUE THREAD

**Issue by dmarzzz** [flashbots/boost-geth-builder#25]
#### System information

`master` branch

#### Expected behaviour

`OnPayloadAttribute` triggers the block building work flow which kicks off block building work in the miner that eventually submits a block to the relay. 

#### Actual behaviour

May be misinterpreting but I can't seem to find anywhere that `OnPayloadAttribute()` gets called. Wondering if it's possibly because of use of reflection or Im missing something. Any pointers would be extremely appreciated :)

**Comment by dmarzzz** [comment]
I see that FCU triggers a block being built here if payloadAttributes exist https://github.dev/flashbots/boost-geth-builder/blob/master/eth/catalyst/api.go#L278 , but don't see how that block ends up being sent to a relay

**Comment by Ruteri** [comment]
See https://github.com/flashbots/prysm - it's our fork that implements the new call.
It behaves a bit like FCU, but it's called always when there's new payload attributes.

**Comment by dmarzzz** [comment]
this was helpful thank you!
