### ISSUE TITLE
geth builder doesn't seem to work

### ISSUE THREAD

**Issue by 0x000000000000000** [flashbots/boost-geth-builder#29]
I ran a builder program, but it did not show a build block
geth start command
<img width="826" alt="截屏2022-09-27 下午7 56 18" src="https://user-images.githubusercontent.com/92365829/192912727-56a4d91f-d5a5-4f73-b421-608ac814fb72.png">
flashbot-prysm start command
<img width="1036" alt="截屏2022-09-28 上午10 13 43" src="https://user-images.githubusercontent.com/92365829/192912812-0036f71f-180d-411d-bc01-f538c5d73f57.png">
geth log
<img width="1332" alt="截屏2022-09-29 上午10 38 08" src="https://user-images.githubusercontent.com/92365829/192926538-f1d500e6-0381-4704-9877-f08bb71ee0ae.png">
prysm log
<img width="1337" alt="截屏2022-09-29 上午10 41 23" src="https://user-images.githubusercontent.com/92365829/192926568-999dc177-963c-4737-b2db-750035efb3d5.png">

**Comment by Ruteri** [comment]
Interesting, I don't see anything wrong with the setup.
Can you try adding `engine` to `--http.api` and connecting Prysm to the EL via `--http-web3provider`?

Can you also post logs from around the beginning of an epoch?

**Comment by 0x000000000000000** [comment]
> 有趣的是，我认为设置了任何问题。 您可以尝试通过添加 Prysm 并将`engine`其`--http.api`连接到 EL`--http-web3provider`吗？
> 
> 您还可以从一个纪元开始发布时的日志吗？

There is still no builder block
Just updated the validator
<img width="1270" alt="截屏2022-09-29 下午7 46 57" src="https://user-images.githubusercontent.com/92365829/193023529-df0f6bb0-5d59-4c4a-b5f9-98322a1178ee.png">

start commonad
geth-builder
<img width="1238" alt="截屏2022-09-29 下午7 43 24" src="https://user-images.githubusercontent.com/92365829/193022847-40a92c3f-7f5c-4767-a8c9-58e78739817b.png">
prysm 
<img width="1337" alt="截屏2022-09-29 下午7 42 45" src="https://user-images.githubusercontent.com/92365829/193022884-045f5964-3981-48de-a2a3-9bc4d98dd354.png">
prysm log
<img width="1323" alt="截屏2022-09-29 下午7 40 52" src="https://user-images.githubusercontent.com/92365829/193022994-2e2e2d9c-7abb-475a-88c7-02890424028f.png">

**Comment by 0x000000000000000** [comment]
If the data is synchronized in the form of snapshot, will it be build block?

**Comment by Ruteri** [comment]
> If the data is synchronized in the form of snapshot, will it be build block?

Yes that's fine. It seems you are just not receiving the block building trigger from Prysm, can you send the exact version (branch/commit) you are building and how you build and run it?

**Comment by 0x000000000000000** [comment]
> > 如果数据以快照的形式同步，会不会是构建块？
> 
> 是的，没关系。看来您只是没有收到来自 Prysm 的块构建触发器，您能否发送您正在构建的确切版本（分支/提交）以及您如何构建和运行它？

v3.1.1

**Comment by Ruteri** [comment]
The default branch in our repo is `develop-boost`, can you try running that?

**Comment by 0x000000000000000** [comment]
> The default branch in our repo is `develop-boost`, can you try running that?



> The default branch in our repo is `develop-boost`, can you try running that?

Do I need to go to cmd/beacon-chain for go build？

**Comment by Ruteri** [comment]
See https://docs.prylabs.network/docs/install/install-with-bazel

**Comment by 0x000000000000000** [comment]
> See https://docs.prylabs.network/docs/install/install-with-bazel



> See https://docs.prylabs.network/docs/install/install-with-bazel

Thanks, I forgot to compile from source code
